import { expect } from 'chai';
import PrepareDataToDisplay from '../../src/components/utility/prepareDataToDisplay';
import savedRepos from './mockSavedRepos';

const repos = [{
  id: 1,
  name: 'name',
  description: 'description description description description description description description description description description description description description',
  language: 'language',
  html_url: 'html_url',
  stargazers_count: 1,
  saved: false,
  topics: ['topic', 'topic', 'topic', 'topic', 'topic', 'topic'],
},
{
  id: 2,
  name: 'name',
  description: 'description description description description description description description description description description description description description',
  language: 'language',
  html_url: 'html_url',
  stargazers_count: 1,
  saved: false,
  topics: ['topic', 'topic', 'topic', 'topic', 'topic', 'topic'],
},
{
  id: 3,
  name: 'name',
  description: 'description description description description description description description description description description description description description',
  language: 'language',
  html_url: 'html_url',
  stargazers_count: 1,
  saved: false,
  topics: ['topic', 'topic', 'topic', 'topic', 'topic', 'topic'],
},
{
  id: 4,
  name: 'name',
  description: 'description description description description description description description description description description description description description',
  language: 'language',
  html_url: 'html_url',
  stargazers_count: 1,
  saved: false,
  topics: ['topic', 'topic', 'topic', 'topic', 'topic', 'topic'],
},
{
  id: 5,
  name: 'name',
  description: 'description description description description description description description description description description description description description',
  language: 'language',
  html_url: 'html_url',
  stargazers_count: 1,
  saved: false,
  topics: ['topic', 'topic', 'topic', 'topic', 'topic', 'topic'],
},
{
  id: 6,
  name: 'name',
  description: 'description description description description description description description description description description description description description',
  language: 'language',
  html_url: 'html_url',
  stargazers_count: 1,
  saved: false,
  topics: ['topic', 'topic', 'topic', 'topic', 'topic', 'topic'],
},
{
  id: 7,
  name: 'name',
  description: 'description description description description description description description description description description description description description',
  language: 'language',
  html_url: 'html_url',
  stargazers_count: 1,
  saved: false,
  topics: ['topic', 'topic', 'topic', 'topic', 'topic', 'topic'],
}];

const result = {
  1: {
    id: 1,
    name: 'name',
    description: 'description description description description description description description descri...',
    language: 'language',
    html_url: 'html_url',
    stargazers_count: 1,
    saved: false,
    topics: ['topic', 'topic', 'topic', 'topic'],
  },
  2: {
    id: 2,
    name: 'name',
    description: 'description description description description description description description descri...',
    language: 'language',
    html_url: 'html_url',
    stargazers_count: 1,
    saved: false,
    topics: ['topic', 'topic', 'topic', 'topic'],
  },
  3: {
    id: 3,
    name: 'name',
    description: 'description description description description description description description descri...',
    language: 'language',
    html_url: 'html_url',
    stargazers_count: 1,
    saved: false,
    topics: ['topic', 'topic', 'topic', 'topic'],
  },
  4: {
    id: 4,
    name: 'name',
    description: 'description description description description description description description descri...',
    language: 'language',
    html_url: 'html_url',
    stargazers_count: 1,
    saved: false,
    topics: ['topic', 'topic', 'topic', 'topic'],
  },
  5: {
    id: 5,
    name: 'name',
    description: 'description description description description description description description descri...',
    language: 'language',
    html_url: 'html_url',
    stargazers_count: 1,
    saved: false,
    topics: ['topic', 'topic', 'topic', 'topic'],
  },
  6: {
    id: 6,
    name: 'name',
    description: 'description description description description description description description descri...',
    language: 'language',
    html_url: 'html_url',
    stargazers_count: 1,
    saved: true,
    topics: ['topic', 'topic', 'topic', 'topic'],
  },
  7: {
    id: 7,
    name: 'name',
    description: 'description description description description description description description descri...',
    language: 'language',
    html_url: 'html_url',
    stargazers_count: 1,
    saved: false,
    topics: ['topic', 'topic', 'topic', 'topic'],
  },
};

describe('PrepareDataToDisplay.js', () => {
  it('checks for saved repos and cuts content to fit', () => {
    const preparedData = PrepareDataToDisplay(repos, savedRepos);
    expect(preparedData).to.deep.equal(result);
  });
});
